image: Visual Studio 2017

environment:
  CMAKE_ARGS: '-G "NMake Makefiles JOM"'
  matrix:
  - QTDIR: C:\Qt\5.9\msvc2017_64
    VCVARS: "vcvars64.bat"
    PLATFORM: x64
  - QTDIR: C:\Qt\5.13\msvc2017
    VCVARS: "vcvars32.bat"
    PLATFORM: x86

init:
- call "%QTDIR%\bin\qtenv2.bat"
- set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
- call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\%VCVARS%" %PLATFORM%
- cd /D "%APPVEYOR_BUILD_FOLDER%"

before_build:
- git submodule update --init --recursive
- mkdir build && cd build
- cmake %CMAKE_ARGS% -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

build_script:
- cmake --build .

after_build:
- cd .. # To gtad sources directory
- 7z a gtad.zip build\gtad.exe

before_test:
- cd ..
- git clone https://github.com/quotient-im/libQuotient.git
- git clone https://github.com/matrix-org/matrix-doc.git
- cd gtad

test_script:
- cd ..\libQuotient
- cmake %CMAKE_ARGS% -DMATRIX_DOC_PATH="../matrix-doc" -DGTAD_PATH="../gtad/build/gtad" .
- cmake --build . --target generate-unformatted-api
- cmake --build . --target all
- cd ..\gtad

# Uncomment this to connect to the AppVeyor build worker
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: gtad.zip
