image: Visual Studio 2017

environment:
  DEPLOY_DIR: gtad-%APPVEYOR_BUILD_VERSION%
  matrix:
  - QTDIR: C:\Qt\5.9\msvc2017_64
    VCVARS: "vcvars64.bat"
    PLATFORM: x64
  - QTDIR: C:\Qt\5.9\msvc2017
    VCVARS: "vcvars32.bat"
    PLATFORM: x86

init:
- call "%QTDIR%\bin\qtenv2.bat"
- set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
- call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\%VCVARS%" %PLATFORM%
- cd /D "%APPVEYOR_BUILD_FOLDER%"

before_build:
- git submodule update --init --recursive
- mkdir build && cd build
- cmake -G "NMake Makefiles JOM" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="%DEPLOY_DIR%" ..

build_script:
- cmake --build .

after_build:
- cmake --build . --target install
- 7z a gtad.zip "%DEPLOY_DIR%\"

# Uncomment this to connect to the AppVeyor build worker
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off

artifacts:
- path: gtad.zip
