language: cpp
dist: bionic

git:
  depth: false

addons:
  apt:
    packages:
    - qt5-default

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: osx
    osx_image: xcode11
    addons:
      homebrew:
        update: true
        packages: [ 'qt5' ]
    before_cache: [ 'brew cleanup' ]
    cache: { directories: [ '$HOME/Library/Caches/Homebrew' ] }

install:
- if [ "$TRAVIS_OS_NAME" != "linux" ]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi

script:
- mkdir build && cd build
- cmake ..
- cmake --build .
