language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - qt5-default

matrix:
  include:
  - os: linux
    compiler: gcc
    env: [ ENV_EVAL="CC=gcc-5 && CXX=g++-5" ]
  - os: linux
    compiler: clang
  - os: osx
    osx_image: xcode8.3
    env: [ ENV_EVAL="brew update && brew install qt5" CMAKE_PREFIX_PATH=/usr/local/opt/qt" ]

install:
- eval "${ENV_EVAL}"

script:
- mkdir build && cd build
- cmake -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" ..
- cmake --build .
