language: cpp
dist: bionic

git:
  depth: false

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - qt5-default
        - qtmultimedia5-dev
        - g++-8
    env:
      [ OVERRIDES="CC=gcc-8 CXX=g++-8" ]
    # Clang 8 is not tested due to std::filesystem linking nightmare
    # Clang 9 + libstdc++ 9.1 should be fine but the latter not available in
    # bionic without PPAs
#  - os: linux
#    compiler: clang
#    addons:
#      apt:
#        packages:
#        - qt5-default
#        - clang-9
#        - libstdc++-9
#    env:
#      [ OVERRIDES="CC=clang-9 CXX=clang++-9 CPPFLAGS=-stdlib=libstdc++" ]
  - os: osx
    osx_image: xcode11.4
    addons:
      homebrew:
        update: true
        packages: [ 'qt5' ]
    before_cache: [ 'brew cleanup' ]
    cache: { directories: [ '$HOME/Library/Caches/Homebrew' ] }

install:
- if [ "$TRAVIS_OS_NAME" != "linux" ]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
- eval ${OVERRIDES}
- git clone https://github.com/quotient-im/libQuotient.git
- git clone https://github.com/quotient-im/matrix-doc.git

script:
- mkdir build && pushd build
- cmake ..
- cmake --build .
- popd
# test
- cd libQuotient
- cmake .
- cmake -DMATRIX_DOC_PATH="../matrix-doc" -DGTAD_PATH="../build/gtad" .
- cmake --build . --target update-api
- cmake --build . --target all

